name: firebase_bloc_analytics
description: Easy integrate you app with multiple analytics tracker, integrate with Firebase Analytics, Crashlytics and others
version: 0.3.1
author: guitcastro <guilherme.torres.castro@gmail.com>
homepage: https://github.com/guitcastro/flutter_bloc_analytics

environment:
  sdk: ">=2.2.0-dev.28 <3.0.0"

dependencies:
  bloc_analytics: ^0.2.0
  firebase_analytics: ^3.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.2.0
  test_api: ^0.2.4
  mockito: ^4.1.0